### ISSUE TITLE
Method to Easily Modify INI Files

### ISSUE THREAD

**Issue by kdorheim** [kdorheim/hectordata#5]
We are going to want some easy way to modify the template ini file to generate ini files for the different scenarios. With CMIP5 there were only 4 scenarios but now there are 9+ scenarios which is why I think we should consider automating this step. 

Things To Think About 
* Do we want to do this in a script? Do we want to design a function? 
* Where should the final ini files live? 
* What are we thinking about unit tests?

**Comment by mnichol3** [comment]
I'm a big fan of automating things like this.

A quick diff of the current `hector_rcp45.ini` and `hector_rcp60.ini` files shows that the only difference between the files are the paths to the emissions files. Will this be the case with the `.ini` files we wish to produce? Or will component variable values be modified as well? (I.e. the value of `tau` for halocarbons)

**Comment by kdorheim** [comment]
I am also a fan of automating these things and there are several ways we could go about it. 

What will be changed on a more regular basis are the emissions and concentration files paths. The parameters (like `tau`, `S`, and `kappa`) will only change if we make changes to the default Hector parameterization. Unless there is a strong case automating parameter changes I don't think we need that capability but could be convinced otherwise.

**Comment by mnichol3** [comment]
Might be a bit overkill, but I wrote a [simple prototype script](https://github.com/mnichol3/hectordata/blob/6a83df276adf45e26e73441456153eafa9bb6ee6/scratch/auto_ini.py) that creates Hector ini input files for scenarios defined in an [input yaml file](https://github.com/mnichol3/hectordata/blob/6a83df276adf45e26e73441456153eafa9bb6ee6/inst/input/config-auto-ini.yml) by replacing values in a [Hector input file template](https://github.com/mnichol3/hectordata/blob/6a83df276adf45e26e73441456153eafa9bb6ee6/inst/input/template.ini). In produced 21 Hector ini files in a 3-run average of 0.106 seconds. 

It's written in Python 3.6, my plan is to translate it if we think this is a good solution
